### ISSUE TITLE
Fix +30 bug

### ISSUE THREAD

**Issue by parker-codes** [parker-codes/finite-state-microwave#4]
If I have 10 seconds entered and I hit `+30` a couple times, it shows `00:70` which is incorrect. It should convert to `01:10` if I hit the `+30` button. If I press `9` twice and then hit the `+30` button, it goes from `00:99` to `02:09`, which is correct.

**Comment by jwlarocque** [comment]
On my (physical) microwave, if you add time in digit form and then add 30 seconds, the display changes to from digit to time mode.  If you then try to add digits again, it clears the time completely and goes back to digit mode (starting at 00:0<your digit>).  If you're okay with that behavior, I think it would solve this issue.

**Comment by parker-codes** [comment]
@jwlarocque Yeah, that sounds good!
